export enum ActionTypes {
  LOGIN = 'ACTION_LOGIN',
  LOGOUT = 'ACTION_LOGOUT',
  ONLOADDATA = 'ACTION_LOAD_DATA',
  ACTIVETABLEITEM = 'ACTIVE_TABLE_ITEM',
  STATEMAODALVIEW = 'STATE_MODAL_VIEW',
  ADDNEWITEM = 'ADD_NEW_ITEM',
}

export enum AsyncActionTypes {
  BEGIN = '_BEGIN',
  SUCCESS = '_SUCCESS',
  FAILURE = '_FAILURE',
}


